spring.config.import=application_prod.properties,application_uat.properties
spring.profiles.active=uat

spring.datasource.url=jdbc:mysql://spring-spring-eazybytes.c.aivencloud.com:13687/eazyschool
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_6-DTLVkp3NIYcw7sxyg
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.javax.persistence.validation.mode=none

spring.data.rest.basePath=/data-api

#debug=true
#trace=true

logging.level.root=INFO
#logging.level.com.eng.it.eazybytes.eazyschool.aspects=ERROR
#logging.level.com.eng.it.eazybytes.eazyschool.controller=ERROR

# Initialize log group eazyschool_error
logging.group.eazyschool_error=com.eng.it.eazybytes.eazyschool.aspects, com.eng.it.eazybytes.eazyschool.controller
# Set log level to log group eazyschool_error
logging.level.eazyschool_error=ERROR

spring.output.ansi.enabled = ALWAYS

eazyschool.pageSize=10

eazyschool.contact.pageSize=5
eazyschool.contact.successMsg=Your message is submitted successfully.

eazyschool.branches[0]=NewYork
eazyschool.branches[1]=Delhi
eazyschool.branches[2]=Paris
eazyschool.branches[3]=Singapore

# Actuator properties
management.endpoints.web.base-path=/eazyschool/actuator
management.endpoints.web.exposure.include=*

spring.application.name=EazySchool

# SpringBoot Admin Server Configuration
spring.boot.admin.client.url=http://localhost:9000
spring.boot.admin.client.instance.metadata.user.name=admin@eazyschool.com
spring.boot.admin.client.instance.metadata.user.password=admin

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true